name: Destroy EKS Cluster

on:
  push:
    branches:
      - setup
    paths:
      - '.github/workflows/destroy-eks.yml'
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'EKS Cluster Name'
        required: false
        default: 'glide-api-cluster'
      region:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'
      force_destroy:
        description: 'Force destroy'
        required: false
        default: false
        type: boolean

jobs:
  destroy-eks:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[destroy-eks]') || github.event_name == 'workflow_dispatch'"

    env:
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name || 'glide-api-cluster' }}
      AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
      TF_VAR_cluster_name: ${{ github.event.inputs.cluster_name || 'glide-api-cluster' }}
      TF_VAR_region: ${{ github.event.inputs.region || 'us-east-1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Cluster Name
        run: |
          echo "Using cluster name: ${CLUSTER_NAME}"
          # Make sure the AWS environment variables are properly set
          echo "AWS_REGION: ${AWS_REGION}"
          echo "TF_VAR_cluster_name: ${TF_VAR_cluster_name}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Check Cluster Status
        id: check-status
        continue-on-error: true
        run: |
          if aws eks describe-cluster --name "${CLUSTER_NAME}" --region "${AWS_REGION}"; then
            echo "cluster_exists=true" >> $GITHUB_OUTPUT
          else
            echo "cluster_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Clean Kubernetes Resources
        if: steps.check-status.outputs.cluster_exists == 'true'
        continue-on-error: true
        run: |
          echo "Cleaning up Kubernetes resources before destroying cluster..."
          aws eks update-kubeconfig --name "${CLUSTER_NAME}" --region "${AWS_REGION}"
          kubectl delete service --all --all-namespaces || true
          kubectl delete deployment --all --all-namespaces || true
          kubectl delete pod --all --all-namespaces || true

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -var="cluster_name=${CLUSTER_NAME}" -var="region=${AWS_REGION}"

      - name: Verify Destruction
        continue-on-error: true
        run: |
          if ! aws eks describe-cluster --name "${CLUSTER_NAME}" --region "${AWS_REGION}"; then
            echo "Cluster successfully destroyed!"
          else
            echo "WARNING: Cluster might still be in the process of being destroyed. Check the AWS Console."
          fi

      - name: Update Status File
        run: |
          mkdir -p cluster-status
          echo "DESTROYED" > cluster-status/status.txt
          echo "${CLUSTER_NAME}" > cluster-status/name.txt
          echo "${AWS_REGION}" > cluster-status/region.txt
          echo "$(date +%s)" > cluster-status/timestamp.txt

      - name: Commit Status
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'whyaneel@gmail.com'
          git add cluster-status/
          git commit -m "Update cluster status to DESTROYED [skip ci]" || echo "No changes to commit"
          git push
